package com.hkmixedkeyboard.ui

import android.content.Context
import androidx.annotation.ColorInt
import com.hkmixedkeyboard.settings.KeyboardTheme

/** Colour tokens shared by every keyboard renderer. Emoji tokens cover surrounding
 * controls only: colour emoji glyphs intentionally have no tint, alpha, or text-colour token. */
data class KeyboardThemeColors(
    @ColorInt val keyboardBackground: Int,
    @ColorInt val keyBackground: Int,
    @ColorInt val specialKeyBackground: Int,
    @ColorInt val spaceKeyBackground: Int,
    @ColorInt val pressedKeyBackground: Int,
    @ColorInt val enterKeyBackground: Int,
    @ColorInt val label: Int,
    @ColorInt val hint: Int,
    @ColorInt val enterLabel: Int,
    @ColorInt val popupBackground: Int,
    @ColorInt val popupLabel: Int,
    @ColorInt val symbolKeyboardBackground: Int,
    @ColorInt val symbolKeyBackground: Int,
    @ColorInt val symbolFunctionKeyBackground: Int,
    @ColorInt val symbolPressedKeyBackground: Int,
    @ColorInt val symbolLabel: Int,
    @ColorInt val symbolIndicatorActive: Int,
    @ColorInt val symbolIndicatorInactive: Int,
    @ColorInt val symbolPopupBackground: Int,
    @ColorInt val symbolPopupLabel: Int,
    @ColorInt val pressedSpecialKeyBackground: Int = 0,
    @ColorInt val keyShadow: Int = 0,
    @ColorInt val divider: Int = 0,
    @ColorInt val candidateBackground: Int = 0,
    @ColorInt val candidateText: Int = 0,
    @ColorInt val candidatePriorityText: Int = 0,
    @ColorInt val candidatePillBackground: Int = 0,
    @ColorInt val candidateSelectedBackground: Int = 0,
    @ColorInt val emojiPanelBackground: Int = 0,
    @ColorInt val emojiCategoryBarBackground: Int = 0,
    @ColorInt val emojiSearchBackground: Int = 0,
    @ColorInt val emojiSearchText: Int = 0,
    @ColorInt val emojiGridPressedBackground: Int = 0,
    @ColorInt val emojiSelectionIndicator: Int = 0,
    @ColorInt val emojiDivider: Int = 0,
    @ColorInt val emojiEmptyStateText: Int = 0,
    @ColorInt val emojiSkinTonePopupBackground: Int = 0,
    @ColorInt val emojiFunctionIcon: Int = 0,
    @ColorInt val emojiFunctionPressedBackground: Int = 0,
    @ColorInt val safeModeBackground: Int = 0,
    @ColorInt val safeModeText: Int = 0,
    @ColorInt val symbolPressedFunctionKeyBackground: Int = 0,
    // Return key when the field declares an action (Go / Search / Send). Zero
    // falls back to the ordinary function-key colour.
    @ColorInt val enterActionBackground: Int = 0,
    @ColorInt val enterActionLabel: Int = 0
) {
    companion object {
        /** Compatibility default for views created before the service injects a palette. */
        fun from(context: Context): KeyboardThemeColors = KeyboardTheme.DARK.toColors()
    }
}

fun KeyboardTheme.toColors(): KeyboardThemeColors = when (this) {
    KeyboardTheme.DARK -> KeyboardThemeColors(
        keyboardBackground = 0xFF202124.toInt(),
        keyBackground = 0xFF3C4043.toInt(),
        specialKeyBackground = 0xFF26282A.toInt(),
        spaceKeyBackground = 0xFF303134.toInt(),
        pressedKeyBackground = 0xFF5F6368.toInt(),
        enterKeyBackground = 0xFF1B9E83.toInt(),
        label = 0xFFE8EAED.toInt(),
        hint = 0xFF9AA0A6.toInt(),
        enterLabel = 0xFFFFFFFF.toInt(),
        popupBackground = 0xFFFFFFFF.toInt(),
        popupLabel = 0xFF202124.toInt(),
        symbolKeyboardBackground = 0xFF15191C.toInt(),
        symbolKeyBackground = 0xFF3C4043.toInt(),
        symbolFunctionKeyBackground = 0xFF2A2C2E.toInt(),
        symbolPressedKeyBackground = 0xFF50575C.toInt(),
        symbolLabel = 0xFFF2F4F5.toInt(),
        symbolIndicatorActive = 0xFFF2F4F5.toInt(),
        symbolIndicatorInactive = 0xFF7B8288.toInt(),
        symbolPopupBackground = 0xFF464C51.toInt(),
        symbolPopupLabel = 0xFFF2F4F5.toInt(),
        pressedSpecialKeyBackground = 0xFF5F6368.toInt(),
        keyShadow = 0x00000000,
        divider = 0x33000000,
        candidateBackground = 0xFF202124.toInt(),
        candidateText = 0xFFE8EAED.toInt(),
        candidatePriorityText = 0xFF8AB4F8.toInt(),
        candidatePillBackground = 0xFF3C4043.toInt(),
        candidateSelectedBackground = 0xFF3C4043.toInt(),
        emojiPanelBackground = 0xFF202124.toInt(),
        emojiCategoryBarBackground = 0xFF26282A.toInt(),
        emojiSearchBackground = 0xFF3C4043.toInt(),
        emojiSearchText = 0xFFE8EAED.toInt(),
        emojiGridPressedBackground = 0xFF5F6368.toInt(),
        emojiSelectionIndicator = 0xFF8AB4F8.toInt(),
        emojiDivider = 0x333C4043,
        emojiEmptyStateText = 0xFF9AA0A6.toInt(),
        emojiSkinTonePopupBackground = 0xFF3C4043.toInt(),
        emojiFunctionIcon = 0xFFE8EAED.toInt(),
        emojiFunctionPressedBackground = 0xFF5F6368.toInt(),
        safeModeBackground = 0xFF3A2E12.toInt(),
        safeModeText = 0xFFF5C26B.toInt(),
        symbolPressedFunctionKeyBackground = 0xFF50575C.toInt(),
        enterActionBackground = 0xFF0B57D0.toInt(),
        enterActionLabel = 0xFFFFFFFF.toInt()
    )

    KeyboardTheme.IOS_LIGHT -> KeyboardThemeColors(
        keyboardBackground = 0xFFD1D5DB.toInt(),
        keyBackground = 0xFFFFFFFF.toInt(),
        specialKeyBackground = 0xFFAEB4BD.toInt(),
        spaceKeyBackground = 0xFFFFFFFF.toInt(),
        pressedKeyBackground = 0xFFC4C8CE.toInt(),
        enterKeyBackground = 0xFFAEB4BD.toInt(),
        label = 0xFF111214.toInt(),
        hint = 0xFF555B61.toInt(),
        enterLabel = 0xFF111214.toInt(),
        popupBackground = 0xFFFFFFFF.toInt(),
        popupLabel = 0xFF111214.toInt(),
        symbolKeyboardBackground = 0xFFD1D5DB.toInt(),
        symbolKeyBackground = 0xFFFFFFFF.toInt(),
        symbolFunctionKeyBackground = 0xFFAEB4BD.toInt(),
        symbolPressedKeyBackground = 0xFFC4C8CE.toInt(),
        symbolLabel = 0xFF111214.toInt(),
        symbolIndicatorActive = 0xFF202326.toInt(),
        symbolIndicatorInactive = 0xFF7D848C.toInt(),
        symbolPopupBackground = 0xFFFFFFFF.toInt(),
        symbolPopupLabel = 0xFF111214.toInt(),
        pressedSpecialKeyBackground = 0xFF969DA7.toInt(),
        keyShadow = 0x26000000,
        divider = 0x33A9AEB5,
        candidateBackground = 0xFFD1D5DB.toInt(),
        candidateText = 0xFF111214.toInt(),
        candidatePriorityText = 0xFF0B57D0.toInt(),
        candidatePillBackground = 0xFFFFFFFF.toInt(),
        candidateSelectedBackground = 0xFFFFFFFF.toInt(),
        emojiPanelBackground = 0xFFD1D5DB.toInt(),
        emojiCategoryBarBackground = 0xFFAEB4BD.toInt(),
        emojiSearchBackground = 0xFFFFFFFF.toInt(),
        emojiSearchText = 0xFF111214.toInt(),
        emojiGridPressedBackground = 0xFFC4C8CE.toInt(),
        emojiSelectionIndicator = 0xFF202326.toInt(),
        emojiDivider = 0x33A9AEB5,
        emojiEmptyStateText = 0xFF555B61.toInt(),
        emojiSkinTonePopupBackground = 0xFFFFFFFF.toInt(),
        emojiFunctionIcon = 0xFF191B1E.toInt(),
        emojiFunctionPressedBackground = 0xFF969DA7.toInt(),
        safeModeBackground = 0xFFE6D3A8.toInt(),
        safeModeText = 0xFF6B4F00.toInt(),
        symbolPressedFunctionKeyBackground = 0xFF969DA7.toInt(),
        enterActionBackground = 0xFF0A6CFF.toInt(),
        enterActionLabel = 0xFFFFFFFF.toInt()
    )
}
